# GramSathi AI

# Notebook 07: AI Recommendation Engine

---

## Objective

The AI Recommendation Engine analyzes the predicted infrastructure status of each village and automatically generates development recommendations.

The recommendations include:

- Roads
- Street Lights
- Water Facilities
- Hospitals
- Schools
- Bus Stops
- Estimated Budget
- Expected Infrastructure Improvement

In [1]:
# ==========================================
# Import Libraries
# ==========================================

import pandas as pd

print("Libraries Loaded Successfully ✅")

Libraries Loaded Successfully ✅

In [2]:
# ==========================================
# Load Village Dataset
# ==========================================

master_df = pd.read_csv("../datasets/processed/village_master_dataset.csv")

master_df

,Village,Road_Length_km,School_Count,Hospital_Count,Bus_Stop_Count,Building_Count,Water_Count,Road_Density,Accessibility_Score,Infrastructure_Readiness_Index,Priority
0,Sadashivgad,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown
1,Majali,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown
2,Asnoti,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown
3,Mudgeri,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown
4,Kanasgiri,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown
5,Hotegali,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown
6,Hankon,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown
7,Joog,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown

# AI Recommendation Rules

The recommendation engine converts infrastructure priority into actionable development suggestions.

These recommendations simulate how a decision support system can assist government authorities in planning rural development.

In [4]:
# ==========================================
# Recommendation Engine
# ==========================================

def recommend(priority):

    if priority == "Critical":

        return (
            "Construct Roads, Install Street Lights, "
            "Build Water Facility, Add Bus Stop, "
            "Improve Drainage"
        )

    elif priority == "Needs Improvement":

        return (
            "Improve Roads, Add LED Street Lights, "
            "Upgrade Water Supply"
        )

    else:

        return (
            "Regular Maintenance and Monitoring"
        )

In [5]:
# ==========================================
# Generate Recommendations
# ==========================================

master_df["Recommendation"] = master_df["Priority"].apply(recommend)

master_df

,Village,Road_Length_km,School_Count,Hospital_Count,Bus_Stop_Count,Building_Count,Water_Count,Road_Density,Accessibility_Score,Infrastructure_Readiness_Index,Priority,Recommendation
0,Sadashivgad,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring
1,Majali,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring
2,Asnoti,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring
3,Mudgeri,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring
4,Kanasgiri,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring
5,Hotegali,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring
6,Hankon,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring
7,Joog,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring

# Budget Estimation

Estimated development cost is calculated based on infrastructure priority.

The budget values are approximate and intended for decision-support simulation.

In [6]:
# ==========================================
# Budget Estimation
# ==========================================

def estimate_budget(priority):

    if priority == "Critical":

        return 5000000

    elif priority == "Needs Improvement":

        return 2500000

    else:

        return 500000

master_df["Estimated_Budget"] = master_df["Priority"].apply(
    estimate_budget
)

master_df

,Village,Road_Length_km,School_Count,Hospital_Count,Bus_Stop_Count,Building_Count,Water_Count,Road_Density,Accessibility_Score,Infrastructure_Readiness_Index,Priority,Recommendation,Estimated_Budget
0,Sadashivgad,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000
1,Majali,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000
2,Asnoti,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000
3,Mudgeri,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000
4,Kanasgiri,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000
5,Hotegali,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000
6,Hankon,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000
7,Joog,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000

In [7]:
master_df["Budget (Lakhs)"] = master_df["Estimated_Budget"]/100000

master_df

,Village,Road_Length_km,School_Count,Hospital_Count,Bus_Stop_Count,Building_Count,Water_Count,Road_Density,Accessibility_Score,Infrastructure_Readiness_Index,Priority,Recommendation,Estimated_Budget,Budget (Lakhs)
0,Sadashivgad,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000,5.0
1,Majali,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000,5.0
2,Asnoti,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000,5.0
3,Mudgeri,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000,5.0
4,Kanasgiri,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000,5.0
5,Hotegali,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000,5.0
6,Hankon,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000,5.0
7,Joog,0.0,0,0,0,0,0,0.0,0.0,0.0,Unknown,Regular Maintenance and Monitoring,500000,5.0

In [8]:
final_report = master_df[[
    "Village",
    "Priority",
    "Recommendation",
    "Budget (Lakhs)"
]]

final_report

       Village Priority                      Recommendation  Budget (Lakhs)
0  Sadashivgad  Unknown  Regular Maintenance and Monitoring             5.0
1       Majali  Unknown  Regular Maintenance and Monitoring             5.0
2       Asnoti  Unknown  Regular Maintenance and Monitoring             5.0
3      Mudgeri  Unknown  Regular Maintenance and Monitoring             5.0
4    Kanasgiri  Unknown  Regular Maintenance and Monitoring             5.0
5     Hotegali  Unknown  Regular Maintenance and Monitoring             5.0
6       Hankon  Unknown  Regular Maintenance and Monitoring             5.0
7         Joog  Unknown  Regular Maintenance and Monitoring             5.0

In [9]:
import os

os.makedirs("../reports", exist_ok=True)

final_report.to_csv(
    "../reports/village_development_report.csv",
    index=False
)

print("✅ Village Development Report Saved Successfully")

✅ Village Development Report Saved Successfully